### ISSUE TITLE
Meeting notes

### ISSUE THREAD

**Issue by ShahNafisRafique** [UNCG-DAISY/Coastal-Image-Labeler#104]
- [x] In order to listen on privileged ports you need root permissions to start the server; this applies to ports < 1024. You may use nginx as a reverse proxy server running on 443 and run your Node JS server alongside on non-privileged ports as an unprivileged user.
https://stackoverflow.com/questions/50112186/error-listen-eacces-0-0-0-0443

I tried a few solutions, none worked. The possible solutions left are to use nginx that runs sudo on 443 and 80 and just does redirects, or write a node server that does the same

**Comment by ebgoldstein** [comment]
ok, i renamed all the `jpg` folders in the `buxtoncoastalcam*` directories to `jpgs` via:

`find . -name 'jpg' -execdir mv {} {}s ';' `
