### ISSUE TITLE
changing image tagging order

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#106]
If we ever wanted to alter image order, we would look @ L276-L289 of
 `Coastal-Image-Labeler/src/dashboard/_server/controllers/v1/user.ts  `

i.e., for active learning, etc..

**Comment by ebgoldstein** [comment]
A key first step here is to have an archive serve images in a random order. This is important for some time-sequence data in the archive now... @ShahNafisRafique , do you have any thoughts on how we could accomplish this?

In v1 of the labeler, the random sequence was the same for every user. We do not neccesarily need this to be the case here in v2. Also the random sequence does not need to be fixed from session to session.. It would also be ok if the randomness was done on the fly — hopefully in the future there will be some computation to determine what image to serve the user.. 

Could there be a field in Catalog collection of the Production Schema that would be something like: {ImageFeed: } and it could be 'sequential', 'random', etc ?

**Comment by ShahNafisRafique** [comment]
Yes that sounds the best, it can be something like
```json
{
    //rest of the catalogs stuff
    imageServeOrder :{
         "type":"random"// or sequential
    }
}
```
I would just make it a json object just incase in the future we want to add options on top of that (like random selection, but only on the middle 50% or something)

I can go ahead and try this now, or wait.

**Comment by ebgoldstein** [comment]
cool, that is a good implementation. 
this would be good to add 'now', and by 'now' i mean in this version of the labeler...

**Comment by ShahNafisRafique** [comment]
Okay I can work on it now then

**Comment by ShahNafisRafique** [comment]
@ebgoldstein The random assignment works, atleast for the dev schema, should we implement for the production schema?

**Comment by ebgoldstein** [comment]
@somyamohanty — I'm looping you into this issue... this is where a recommender based on clustering could fit in..

**Comment by ebgoldstein** [comment]
this has been closed for the time being... more complicated `imageServeOrder`'s are being planned

**Comment by ShahNafisRafique** [comment]
random server order ,sequential server order (with random as backup if an archive doesn't have sequential order) is done
