### ISSUE TITLE
Tag as all water button

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#107]
Currently there is a `tag as all water` button. Unfortunately this does not pertain to all catalogs.

is there a way that we can have the text of this button (and the entry into the DB) change based on the questions set? 

for example, on the Dune Collision and Tairua images, this button should say:

"tag as unusable"... which a user would check it the image was too blurry, foggy, rainsplashed, or the camera was not functioning correctly.

**Comment by ShahNafisRafique** [comment]
I can incorporate it into the question set, where buttons in a question set are viewed as "quick" presets or like a speed dial thing.

**Comment by ShahNafisRafique** [comment]
So I tried this out on the dev schema, I simply added a new question to the `questions` section of the question set as follows
```json
{
	"type": "buttonSubmit",
	"required": false,
	"label": "Quick Submit Buttons",
	"docLink": "https://uncg-daisy.github.io/Coastal-Image-Labeler/docs/question_sets/stormQuestionSet#textbox",
	"key": "quickSubmitButtons",
	"tag": {
		"water": true
	},
	"buttons": [
		{
			"label": "Tag as Water",
			"tag": {
				"water": true
			},
			"key": "tagAsWater"
		}, 
		{
			"label": "Tag as Unusable",
			"tag": {
				"unusable": true
			},
			"key": "tagAsUnusable"
		}
	]
}
```
@ebgoldstein

**Comment by ebgoldstein** [comment]
this looks good to me.. I think for the storm catalogs, we only want that water button... for all others, we only want a unusable button... 

(so a customizable speed dial/quick submit idea is a good one...)

**Comment by ShahNafisRafique** [comment]
Should I do that, or let you do that for the production schema?

**Comment by ebgoldstein** [comment]
I will add those to the production schema!

**Comment by ebgoldstein** [comment]
i also moved the water Q up to be the first Q... so its easier for users..
