### ISSUE TITLE
Tag permissions removed

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#108]
Eventually some Catalogs and archives will need to be removed from the VM. 

-if users still have permission to tag a catalog/archive, and the image is gone, will there be an error? (i.e., 'image not found')

- I noticed that if i remove someones permissions to tag a catalog/archive, but they have already started tagging it and it's listed in their table on the landing page. If they click the table to label the images, they get an error stating that they 'no longer have permissions'

How do we deal with catalogs/archives needing to be removed from the VM, but the catalog/archive entry still appearing in the users 'table' when they log in?

**Comment by ShahNafisRafique** [comment]
If you remove the image from `assignedImages` field of the user document then it wont show up on the table.

**Comment by ebgoldstein** [comment]
great — thx.. I see that now.
