### ISSUE TITLE
keyboard shortcut for submit button?

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#109]
maybe this is a crazy idea?

**Comment by ShahNafisRafique** [comment]
I think it might be a little bit crazy 😂. Just cause it would save like 1 second and also because it would be unorthodox in terms of form submission.

*and also because I have no clear clue on how to do it*

**Comment by ebgoldstein** [comment]
ok, let's forget i even said it...
