### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by dbuscombe-usgs** [UNCG-DAISY/Coastal-Image-Labeler#111]
Fantastic usability - this is great stuff. I've labelled a few dozen and intend to keep going. Will downloads be supported in future? If so, which model? everyone's labels/imagery or only the ones an individual user has labelled? or other? Interested in that discussion

**Comment by ebgoldstein** [comment]
for right now, if you need something, just let me know and I can pull it. 

The raw dumps (nested `json`s) require access to our collections in MongoDB... There is no API endpoint for data (yet... that has not been fully thought through)

I have not fully determined the workflow or where it will live (needs to have a doi), but my plan was to dump it every week (via a `cron` job, etc.)  and provide all labels for the public data on the server (e.g., NOAA ERI images). In the ideal world it would be automated... every week dump the json, test for differences, if different format into a csv, send to zenodo, published with (incrementing) doi..

As for the data structure: My hope was to keep the labeling anonymous, and not associate a group of labels with a given user .. so labels will be served for each image, not each user.. so output would look similar to the Florence figshare data.. 

I am very happy to hear other ideas @dbuscombe-usgs ...

**Comment by dbuscombe-usgs** [comment]
Thanks for the info - sounds like a good plan. I agree csv or json format probably best considering the multi-label nature of the data. A regular data dump sounds good. It would also be good to try to weed out outlier classifications using an automated process, by way of dataset QA. I could help with that, if interested. Those images/classifications could be removed or perhaps flagged as dubious

**Comment by ebgoldstein** [comment]
good point re: QA..that deserves its own issue moving forward

**Comment by ebgoldstein** [comment]
@dbuscombe-usgs —we migrated this discussion re: data downloading to: https://github.com/UNCG-DAISY/Coastal-Image-Labeler/issues/139..

I'll keep thi issue open until we solve, and then close them both..

**Comment by ebgoldstein** [comment]
subsumed by #139
