### ISSUE TITLE
Check daily export cron job

### ISSUE THREAD

**Issue by ShahNafisRafique** [UNCG-DAISY/Coastal-Image-Labeler#115]
Doing a quick search, found [here](https://stackoverflow.com/questions/34735908/scheduling-file-every-1-hour-using-nodejs) I can have cron jobs be ran by node js. If I use [this](https://crontab.guru/#00_12_*_*_*) It says `00 12 * * *"`means `at 12 noon" run this script`. The only issues would be to error check/test the job since I would have to wait 1 day.

I will come back and close this tomorrow if it works

**Comment by ebgoldstein** [comment]
I see the backup @ShahNafisRafique ....

**Comment by ShahNafisRafique** [comment]
I saw that too, but it was at 8am est because I forgot the server is on UTC time, so it should do it now at 16 UTC = noon est @ebgoldstein
