### ISSUE TITLE
Show message when no more images to tag for archive.

### ISSUE THREAD

**Issue by ShahNafisRafique** [UNCG-DAISY/Coastal-Image-Labeler#116]
Currently shows undefined with empty image.

**Comment by ebgoldstein** [comment]
<img width="796" alt="Screen Shot 2020-06-22 at 4 50 54 PM" src="https://user-images.githubusercontent.com/5330599/86390507-2fa12f00-bc66-11ea-9d8b-fc2102b4451d.png">

**Comment by ShahNafisRafique** [comment]
![yesss](https://user-images.githubusercontent.com/38015120/86491041-8296e700-bd37-11ea-952a-08f5650bdaf8.PNG)
@ebgoldstein I added a fix to show a error message saying there are no more images to tag, when you can, can you please check it out and see if it works for you as well. 

For testing it I pretty much copied the `imagesTagged` array over to my user.

**Comment by ebgoldstein** [comment]
i see it! — nice work!

**Comment by ebgoldstein** [comment]
actually i will let you close this when you revert the MongoDB back

**Comment by ShahNafisRafique** [comment]
Done
