### ISSUE TITLE
Optimize storing the list of already tagged images

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#119]
As user tags more images and is assigned more archives, the table on the Labeler home page will take longer to load (as it queries the DB). There could be a new, faster way to deal with this.

**Comment by ShahNafisRafique** [comment]
@ebgoldstein Production site is up, can you go and see if the optimization looks nice and then close the issue if so.

**Comment by ShahNafisRafique** [comment]
- [ ] Change `imagesTagged` to be a JSON

- [ ] Create script to refactor current list of images already tagged by people

- [ ] Check `getUserResumeInfo` under catalogs controller

- [ ] Check user model under `User.ts` and index.d.ts

- [ ] Updated `getAssignedImage` and `updatedTaggedImages` in user controller

**Comment by ShahNafisRafique** [comment]
@ebgoldstein The optimization should be done now, can you go ahead and see if it works nicely. If you can, can you also tag a new image and see it being assigned to the `assignedImages` property and then once its tagged see if it gets transferred to `imagesTagged`, it looks like it works from my end.

**Comment by ebgoldstein** [comment]
1 minute, table still blinking

**Comment by ShahNafisRafique** [comment]
Okay working on a bug

**Comment by ShahNafisRafique** [comment]
@ebgoldstein Okay can you try again

**Comment by ebgoldstein** [comment]
2.5 seconds..

1 image tagged in `Florence/20180919a_jpgs`

**Comment by ShahNafisRafique** [comment]
Okay so everything works now. Good to close?

**Comment by ebgoldstein** [comment]
Yep, can be closed
