### ISSUE TITLE
Handling of images with same name, under same archive in different folders

### ISSUE THREAD

**Issue by ShahNafisRafique** [UNCG-DAISY/Coastal-Image-Labeler#147]
When testing image entry for Florence I noticed a duplication issue. The image `P25959646.jpg` appears in two different archives

![fileissue](https://user-images.githubusercontent.com/38015120/91651460-f533f280-ea5a-11ea-859e-36b28c9bcfb8.PNG)

Archives 16a and 16b. The 3 entries into the database that are created are (more or less,I stripped the non relevant info)

```
{
name: 'P25959646.jpg'
archive: '16a'
},
{
name:'P25959646.jpg'
archive:'16b'
},
{
name:'P25959646.jpg'
archive:'16b'
}
```

As you can see theres two entries that are the same, and the model is setup right now to have the (name,archive) pair be unique. The reason why `jpgs/bak/P25959646.jpg` and `jpgs/P25959646.jpg` resolve to the same name is that the name field is only the image name, and the `path` field will contain the full image path.

My question is
**How should we solve this issue?**

I have a few solutions

1. Remove the unique requirement for the (name,archive) pair since images with the same name cant exist in the same folder and the name of the images is largely irrelevant (I think they are location based? So it would make sense for multiple images to have the same name). **Easiest solution that handles all cases**

2. Manually remove all `/bak` folders cause I think they are backup folders? **Hardest**

3. Remove the unique requirement for the (name,archive) pair and change it to (name,path) pair, but I am not sure if that will fix all future issues. **Might cause issues in the future**

I think we should go with option 1 (which I will do for now), but its up to you @ebgoldstein

**Comment by ebgoldstein** [comment]
the existence of the `/bak` folder is strange: it only exists this archive — `20180916b_jpgs` — and duplicates images that are in another archive `20180916a_jpgs`. Just checking one image (`S25972247`) from both `20180916a_jpgs` and `20180916b_jpgs/bak` suggests the `bak` is just duplicates..

from `20180916b_jpgs/bak`:
![bak:S25972247](https://user-images.githubusercontent.com/5330599/91662901-58517380-eab3-11ea-81c4-469a93272951.jpg)

and from `20180916a_jpgs`
![S25972247](https://user-images.githubusercontent.com/5330599/91662918-6ef7ca80-eab3-11ea-8e4b-1db0aa5647ad.jpg)

 my suggestion is we just delete this /bak/ folder `20180916b_jpgs` and reload 20180916b_jpgs into the archive. 

I think the unique name-archive pair is actually a good check for this behavior, so can the CLI just throw an error?
