### ISSUE TITLE
tag.water and consistency in the Image Collection

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#159]
We are running into an situation where we need consistency re: `tag.water` for data export. 
For example,  when an image is tagged as water, it has `tags.water = TRUE` and  no other `tags` (regardless of the question set).

When an image is not water,  and there is no `tags.water`, instead we have tags for all the Questions..

this consistency is an issue during data export... For images that are tagged water, we need all the questions to still be there in the `tags` object, but have a NULL or NAN value.. 

For images that are not tagged water, we need `tags.water` to have a NULL or NAN value.. 

does this make sense?

**Comment by ebgoldstein** [comment]
@ShahNafisRafique , I'll let you close this when you are satisfied?

**Comment by ShahNafisRafique** [comment]
Yes
