### ISSUE TITLE
code to interact w/ database (connect, modify)

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#160]
@ShahNafisRafique — you mentioned uploading some code to interact with the DB. This will be helpful for me re: loading up new key:value pairs to the path object.

**Comment by ShahNafisRafique** [comment]
Yes I can get to that tomorrow/on the weekend. I will also update the docs for that as well.

**Comment by ebgoldstein** [comment]
@ShahNafisRafique , I'll let you close this when you are satisfied?

**Comment by ShahNafisRafique** [comment]
Yea I think its done, any future issues can be handled later
