### ISSUE TITLE
Assign image API

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#165]
I'm just putting this here as something to think about...

I asked @ShahNafisRafique if there could be a link from the map to the labeler for people to immediately label an image that they see is a false positive (prediction is washover, but no washover in image)..

He replied:

>They would need to have permissions to tag that catalog and have an account. If they have >both then we can make a API where we can assign a specific image to a user, or make a new >entry in the `assignedImages` table.

_Originally posted by @ShahNafisRafique in https://github.com/UNCG-DAISY/StormImpactMap/issues/20#issuecomment-695843955_

**Comment by ebgoldstein** [comment]
i see there is an API route for `assignedImages`: 
https://uncg-daisy.github.io/Coastal-Image-Labeler/docs/code_doc/routes/overview/

**Comment by ShahNafisRafique** [comment]
So that link @ebgoldstein is for just general purpose querying. I think I can make a route that given a `userID` and `imageID` can assign that image to that user (if they are NOT part of that catalog it can auto add them to it)

**Comment by ebgoldstein** [comment]
also — people might not even be a user when they hit the button on the map to label the image... so imagine that scenario...

**Comment by ShahNafisRafique** [comment]
Okay so should I do anything about that or just let you handle it?

**Comment by ebgoldstein** [comment]
i think if you are interested in building that route — that would be cool..

**Comment by ebgoldstein** [comment]
we are tabling this for now...
