### ISSUE TITLE
Ambiguity in questions and broken '?' links that would offer clarification

### ISSUE THREAD

**Issue by dbuscombe-usgs** [UNCG-DAISY/Coastal-Image-Labeler#166]
you may know this already, but just in case ... tooltip links for development type, etc, are broken. Links to https://uncg-daisy.github.io/Coastal-Image-Labeler/docs/question_sets/stormQuestionSet get 404 errors

tagging today!

**Comment by dbuscombe-usgs** [comment]
BTW, I noticed this when I was seeking guidance on what to tag as 'inland' - it's not a category I have a intuition for - almost all scenes contain 'inland' portions (i.e. land above sea level? land beyond backbarrier marshes? ) because the images have huge spatial footprints, so I worry it would be routinely mislabeled or inconsistently labeled. If it was broken up into more specific categories, I think there might be less confusion. Perhaps inland waterways, supra-tidal marshes, etc. Or is 'inland' supposed to be for scenes that contain no sea or estuarine water?

I admit I also struggle with river - if I've seen any rivers so far, I don't know if I have because they are broad-mouthed and - without any prior knowledge of this area (for example, people who have never been to coasts of FL, SC, NC, GA, etc) I actually find it hard to make that call. Could be a river - could be an estuary or inlet - from a single image it is impossible to tell

**Comment by dbuscombe-usgs** [comment]
Of course, the second I post this issue, I get my very first bona fide 100% sure this is a river!! (Isaias - P21776651.jpg)

**Comment by ebgoldstein** [comment]
https://coastalimagelabeler.science/api/image/5f5c1c37016e86108aec3cb3/compressed

**Comment by ebgoldstein** [comment]
yeah, we upt this in for Florence, since there are lots of image only tiles (see below)... I should be more clear that this is really for rivers, not tidal channels, etc.

<img width="892" alt="Screen Shot 2020-10-06 at 12 14 53 PM" src="https://user-images.githubusercontent.com/5330599/95228751-b61d5d80-07cd-11eb-9336-82decaa58371.png">

**Comment by ebgoldstein** [comment]
i would  only mark 'active' overwash fans... not the vegetated ones (those in dashed box below)... is that what you mean?
<img width="765" alt="Screen Shot 2020-10-06 at 12 17 34 PM" src="https://user-images.githubusercontent.com/5330599/95229059-1d3b1200-07ce-11eb-9376-d3fc20244eab.png">

**Comment by dbuscombe-usgs** [comment]
Yes, that's what I thought, just needed clarification. I assume now that 'inland' is 'entirely inland'

On the river class, for example this one looks like a river but I couldn't distinguish this from an estuary https://coastalimagelabeler.science/api/image/5f5c1c37016e86108aec3cef/compressed

**Comment by dbuscombe-usgs** [comment]
fyi, for now I'm skipping images like this where I can't tell if the dominant class is river or estuary: https://coastalimagelabeler.science/api/image/5f5c1c37016e86108aec3cab/compressed

No biggie, but i suggest breaking those classes up or giving some guidance over what to when you see unbroken water but not enough context to make a geomorphic distinction

**Comment by ebgoldstein** [comment]
i think you can label it as either/both, and write a comment... the last 2 qs are the least important RN since they are so ambiguous... your feedback on breaking up into classes is what we needed... However, if you skip then we don't get info on washover, damage, development, etc.

**Comment by ebgoldstein** [comment]
if it were me, i would label as both, and not write comment... (for speed)

**Comment by dbuscombe-usgs** [comment]
This is really minor but on the same thread. Consider just embedding a tiny image such as this one that will show everyone - at a glance - what the different sallenger categories are without them having to look it up. Would ensure greater consistency, I think: https://www.researchgate.net/profile/Saber_Elsayed2/publication/315819318/figure/fig20/AS:614191757004821@1523446134353/21-Storm-surge-regimes-defined-by-Sallenger-2000-De-Vet-2014.png

**Comment by dbuscombe-usgs** [comment]
One last suggestion (for now, I promise!). I haven't yet seen any damage, but when I do, I am taking infrastructure literally (roads, pipelines, power lines), as opposed to structures/superstructures (residential homes, commercial buildings, walls, jetties, piers, groynes, etc) or counting any damage to any man-made object?

**Comment by ebgoldstein** [comment]
arg — it should be damage to structures too... 
I will correct that RN...

**Comment by ebgoldstein** [comment]
should be fixed now

**Comment by dbuscombe-usgs** [comment]
yep, fixed - love that integration!!!

**Comment by dbuscombe-usgs** [comment]
I must say you all have done a great job with this and I'm excited to help test and improve! The app is super intuitive, fast - you've made some excellent design choices.

**Comment by dbuscombe-usgs** [comment]
I have first-hand recent experience with working with a dataset that has about 20% error in the labels (the TAMUCC dataset I am using to teach MLMONDAYS), so my comments this morning have been in service of catering to the unsure and pedantic among us, to absolutely avoid that happening here

**Comment by dbuscombe-usgs** [comment]
It would be really interesting to see how well a damage/no damage classifer would perform at this scale. For example, https://coastalimagelabeler.science/api/image/5f5c1c37016e86108aec3c4f/original

There are more buildings in this scene that are undamaged than damaged, but those damaged are damaged quite badly

**Comment by dbuscombe-usgs** [comment]
On occasion I get agricultural land that I consider 'developed' (roads and crop rows) but would likely screw a classification like this up, since its really semi-natural and probably nothing like the other developments with structure. Maybe just a note in the docs to say 'developed' means human settlements and objects or whatever

e.g. https://coastalimagelabeler.science/api/image/5f5c1c37016e86108aec3ca8/original

**Comment by ebgoldstein** [comment]
that makes sense. FWIW I would say its developed too...

**Comment by dbuscombe-usgs** [comment]
I tagged 100 Florence and 100 Isaias images

**Comment by dbuscombe-usgs** [comment]
I may have screwed up those few that I skipped because of the river issue (above) - sorry!

**Comment by ebgoldstein** [comment]
Isaias was hard, i thought... lots of zooming... We have a shade over 800 labels total right now (spread over the 300 images)

**Comment by dbuscombe-usgs** [comment]
i usually have to zoom to tell if there is damage, but i feel like i can usually identify the other categories without the zoom

**Comment by dbuscombe-usgs** [comment]
100 Michael images tagged. LOTS of damage in that set

**Comment by ebgoldstein** [comment]
I added some sentences in the docs

**Comment by ebgoldstein** [comment]
https://github.com/UNCG-DAISY/Coastal-Image-Labeler/commit/3b4106c959e4a33ad7eb04738b1a34eccabb4886 finally added real instructions for labelers
