### ISSUE TITLE
Archives Taggable true / false

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#168]
Archives should be marked as `taggable`. and this functionality should work.. 

this will be used for the priority catalog... were new archives will be added, and old ones will be decommissioned (but not removed from the DB)

true means a user sees the archive them in the table.
false means the user does not see the archive them in the table.

**Comment by ebgoldstein** [comment]
i can test this...

**Comment by ebgoldstein** [comment]
it seems to not be implemented.

Mongo:
<img width="354" alt="Screen Shot 2020-10-08 at 9 44 55 PM" src="https://user-images.githubusercontent.com/5330599/95532846-9b0a4380-09af-11eb-8e3c-478ef845f3e0.png">

Labeler:
<img width="807" alt="Screen Shot 2020-10-08 at 9 45 17 PM" src="https://user-images.githubusercontent.com/5330599/95532849-9cd40700-09af-11eb-9997-87dcd9bb9104.png">

**Comment by ShahNafisRafique** [comment]
When 1/2 archives are marked false
![image](https://user-images.githubusercontent.com/38015120/95667101-47beff00-0b2f-11eb-96a9-8a90c3da1de7.png)
![image](https://user-images.githubusercontent.com/38015120/95667104-4beb1c80-0b2f-11eb-8ec1-7021e26fec13.png)

When both are marked false

![image](https://user-images.githubusercontent.com/38015120/95667107-59a0a200-0b2f-11eb-836b-759ab84b6554.png)

**Comment by ShahNafisRafique** [comment]
I also did this for catalog too. So only taggeable catalogs and archives should show up
