### ISSUE TITLE
Image size on labeler

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#169]
the full image should be visible... small strip on the top and bottom are currently cut off...

**Comment by ebgoldstein** [comment]
edge case:
![original](https://user-images.githubusercontent.com/5330599/95531097-b5432200-09ad-11eb-8f43-0c5960533670.jpg)

<img width="852" alt="labeler" src="https://user-images.githubusercontent.com/5330599/95531107-bb390300-09ad-11eb-9167-309e4c1a0e34.png">

**Comment by ShahNafisRafique** [comment]
Done, image is resized to fit and now theres even a loading image
