### ISSUE TITLE
Save drawings as image

### ISSUE THREAD

**Issue by ShahNafisRafique** [UNCG-DAISY/Coastal-Image-Labeler#184]

**Comment by ebgoldstein** [comment]
After speaking with @dbuscombe-usgs, i think SVG is the preferred save format

**Comment by ebgoldstein** [comment]
@ShahNafisRafique did this via https://github.com/UNCG-DAISY/Coastal-Image-Labeler/commit/4ac268036ed5a1389494019deeef5d8f76e009c5.
