### ISSUE TITLE
on select of storm

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#29]
show Storm Name, Storm Year, Image Number, Link to Storm Wikipedia page

**Comment by ShahNafisRafique** [comment]
added Storm Name, Storm Year, and wiki page.

I will do image number a little bit later as I kind of have to redesign the stepper

**Comment by ShahNafisRafique** [comment]
![images](https://user-images.githubusercontent.com/38015120/83518576-9c2edf80-a4a8-11ea-8ba1-5dd58d6b4d0e.PNG)

**Comment by ebgoldstein** [comment]
this looks good. 'Storm' is misspelled on the top part. And we might want to change "Pick a storm" and "Pick an archive from that storm" to "Pick a catalog", "Pick an archive from that catalog"

**Comment by ShahNafisRafique** [comment]
![fixed](https://user-images.githubusercontent.com/38015120/83519341-c7fe9500-a4a9-11ea-9840-e5a17cc21d85.PNG)
Fixed, just have to rename some internal variables with the word storm in them now.
