### ISSUE TITLE
create CLI to add storms/archives/images

### ISSUE THREAD

**Issue by ShahNafisRafique** [UNCG-DAISY/Coastal-Image-Labeler#40]
There are 3 CLI commands I can think of, `addStorm`, `addArchive`, and `addImage`

For all 3 im thinking of just having them read a JSON file, that way you can just feed it a JSON file and it will read it rather then having to type out a bunch of options

For example, `addStorm path/to/json/file.json` where `file.json` would look something like this,

```json
[
	{
		"name":"storm1",
		"path":"path/to/storm1/",
		"dateAdded": "Optional, if not provided will use todays date",
		"stormInfo":{
			"year":2020,
			"link":"www.yes.com",
			"description":"this is a storm called storm1"
		},
		"taggable":true,
		"autoInsertArchives":true,
		"autoInsertImages":true
	},
	{
		"name":"storm2",
		"path":"path/to/storm2/",
		"dateAdded": "Optional, if not provided will use todays date",
		"stormInfo":{
			"year":2021,
			"link":"www.no.com",
			"description":"this is a storm called storm2"
		},
		"taggable":true
	},
	{
		"name":"storm3",
		"path":"path/to/storm3/",
		"dateAdded": "Optional, if not provided will use todays date",
		"stormInfo":{
			"year":2022,
			"link":"www.maybe.com",
			"description":"this is a storm called storm3"
		},
		"taggable":true
	}

]
```
There would be an option called `autoInsertArchives` that would look at the subfolders of a storm and create those as archives if none exists and `autoInsertImages` which would look at an archive and create the images for that archive if they dont exist. This way you have some flexibility. So you can add a storm but not archives just incase the archives havent been made yet or something.

@ebgoldstein How would you like it? Do you think this is okay or would you like me to create this and then try it out?

**Comment by ebgoldstein** [comment]
CLI commands are a good idea. 
Adding a storm makes sense.
Adding an archive makes sense.
I don't think I will ever add individual images (just directories of images, which is an archive).

There is a chance in the future we will add groups of images that are not 'storms', but instead collections of images that are grouped in some other way... So it's sort of like 1 org. level above a storm..  You don't neccesarily need to do this, but i want to let you know i was thinking about it..
