### ISSUE TITLE
Table on home page for each user

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#43]
something that looks like this: 

| Storm   | Archive |  # pics tagged | # pics total | |
| ------------- | ------------- |----- | ----- | ----- | 
| Florence | 20180919a | 0 | 1045 | `Start` |
| Florence | 20180919b | 20 | 3432|`Start` |
| Florence | 20180919c | 400 | 4532|`Start` |
| Michael | 20181012b | 400 | 453 |`Start`|

**Comment by ShahNafisRafique** [comment]
This is the current table for the home page right now. I can work on showing `Storm`, `# pics tagged` and `Total` a little bit later as im not sure 100% on how I want to implement that @ebgoldstein .

![asdasdsadad](https://user-images.githubusercontent.com/38015120/82133916-66f37380-97bf-11ea-9801-53c81846438a.PNG)

**Comment by ShahNafisRafique** [comment]
You can either click the button, or click the row

**Comment by ShahNafisRafique** [comment]
![table](https://user-images.githubusercontent.com/38015120/83488265-8b677500-a47a-11ea-9152-46786c714f98.PNG)
@ebgoldstein This is the table for resuming on the home page, is there anything else you would like to add?

**Comment by ebgoldstein** [comment]
i think this looks great. 2 notes:

1. what is the difference between 'you tagged' and 'total tagged'? I would just show the number of images that the user has tagged, and then put this under the heading 'total tagged' 

2. you can remove the column label 'Resume' — the green Resume buttons will be enough..

**Comment by ShahNafisRafique** [comment]
1. The difference between `you tagged` is that its how many images that user has tagged of that archive. `Total tagged` is how many images of this archive have been tagged,since there is only one user both numbers are going to be the same.

2. Done

3. I added the row clicking just because I was too lazy to move to the resume button, and saw that I could do it. I can remove it.

**Comment by ebgoldstein** [comment]
ok...thx for the clarification...  I would just show the number of images that the user has tagged, and then put this under the heading 'total tagged'

**Comment by ShahNafisRafique** [comment]
Okay that is done
