### ISSUE TITLE
Catalog-specific questions

### ISSUE THREAD

**Issue by ShahNafisRafique** [UNCG-DAISY/Coastal-Image-Labeler#47]

**Comment by ebgoldstein** [comment]
ok, so i have a use-case. I have some images that i want to classify into 1 of 4 categories (radio button) and a notes box:

- Collision
- Pre/Post or Close
- No impact
- Unusable (blurry/dark/etc.)

and a notes tab

this simple question set can be called 'Dune Collision'... (vs the one we have been using, which should be called 'post-storm')

**Comment by ShahNafisRafique** [comment]
Would there common set of questions across all catalogs (other then skip and tag as water)

**Comment by ebgoldstein** [comment]
no.
skip is always good to have, but tag as water could be removed for this one (but i think the way its coded in now, it would be difficult to remove, right? if so, its fine for it to be included)

**Comment by ShahNafisRafique** [comment]
It would be difficult to move it around right now. I do plan on after getting the initial version of the dashboard up to start implementing the question sets and rework how I handle the form.
