### ISSUE TITLE
Handle archives having a /jpg folder

### ISSUE THREAD

**Issue by ShahNafisRafique** [UNCG-DAISY/Coastal-Image-Labeler#54]

**Comment by ShahNafisRafique** [comment]
@ebgoldstein So something I didnt notice was that the archives have subfolders in this case just 1 being called `jpgs`. Right now I semi hardcoded in `/jpgs` meaning I have a extra parameter in my functions to accept an append path but, no way for the user to say that in the CLI. How would you like to handle this? Should I just assume all archives will have `/jpgs` or is there something else in mind you would like to do.

**Comment by ebgoldstein** [comment]
can we just say in the docs that there needs to be a folder called `jpgs` in the archives that holds all the pics?

**Comment by ShahNafisRafique** [comment]
yes we can. Worse case is I can have the CLI just create catalogs and archives, the admin fixes the path and then tells the CLI to add the images.
