### ISSUE TITLE
Duplicate archives?

### ISSUE THREAD

**Issue by ShahNafisRafique** [UNCG-DAISY/Coastal-Image-Labeler#57]
So while working on #55 and making the CLI more informative in its logging I noticed that there where 4 archives that had alot of duplicate images, meaning that another archive has images with the same name. These are the archives with duplicate images.

The image in the () is one of the images of that archive that already exist.

`20180916b_jpgs` - (P25959661.jpg) due to 20180916a_jpgs already existing
`20180919c_jpgs` - (C26249895.jpg) due to 20180919a_jpgs already existing
`20180920b_jpgs` - (C26351954.jpg) due to 20180920a_jpgs already existing
`20180920c_jpgs` - (C26377219.jpg) due to 20180920b_jpgs already existing

I only looked at one of the images and it does appear to be true duplicate, but I can say for sure if all are like that because there is a couple of thousand duplicates

The reason they are duplicates is because before I insert an image in I check to see if an other name with the same name or same path exists. I think I can get around this issue by basically saying that two images with the same name under different archives can be entered in. Right now the `id`(name of the image) and `path` have to both be unique inorder to **NOT** be a duplicate.

So which way would you like to go @ebgoldstein ? 
- [x] Keep as is, images have to have unique names across all archives
- [x] Or images with the same name can exist under different archives.

and more of an FYI, it took 9 minutes to enter all 11.5k images. I could maybe make it faster, but im not sure.

**Comment by ShahNafisRafique** [comment]
Here is what the console log looks like and how many dups of each archive there are.

![log1](https://user-images.githubusercontent.com/38015120/83258704-c4ef6600-a184-11ea-841a-2f22336108d7.PNG)
![log2](https://user-images.githubusercontent.com/38015120/83258710-c6b92980-a184-11ea-97a2-922558fc36c3.PNG)

**Comment by ebgoldstein** [comment]
For now, I think 'as is' is fine. I think its good to know this issue exists...

**Comment by ShahNafisRafique** [comment]
It should be an easy change, I can try it soon and see if it works.

**Comment by ShahNafisRafique** [comment]
For an update on this, two images that are the same (same name) under two different archives will be put in to the DB. There is not a lot of dup images, around 400-500 out of 28.2k.
