### ISSUE TITLE
Instructions/Examples

### ISSUE THREAD

**Issue by ShahNafisRafique** [UNCG-DAISY/Coastal-Image-Labeler#74]
# Instructions
- [x] How to get ability to tag
- [x] How to select catalog
- [x] How to select archive
Link to mkdocs page where this would go [here](https://psi-dashboard.readthedocs.io/en/latest/user_documentation/tagging_process/)
which would be this file `docs/user_documentation/tagging_process.md`
# Examples
- [x] Examples and explanation of each option for each question/option
Link to mkdocs page where this would go [here](https://psi-dashboard.readthedocs.io/en/latest/user_documentation/examples/storm_impact/)
which would be this file `docs/user_documentation/examples/storm_impact.md`

**Comment by ShahNafisRafique** [comment]
Added paths to files to edit

**Comment by ebgoldstein** [comment]
i added text, i will eventually add images...
