### ISSUE TITLE
Update code documentation

### ISSUE THREAD

**Issue by ShahNafisRafique** [UNCG-DAISY/Coastal-Image-Labeler#75]
- [x] Packages
- [x] Project structure,include CLI
- [x] Fix images on auth0
~~- [ ] Add data export with CLI~~
- [x] Update extending with new question set system

**Comment by ebgoldstein** [comment]
- [ ] CLI for uploading new images (and json structure)*
 - [ ] MongoDB
 - [ ] deployment on VM

(* I have some new images on the vm ready to import)

**Comment by ShahNafisRafique** [comment]
What would you like for the MongoDB docs? I already have a page on how to use the CLI [here](https://uncg-daisy.github.io/Coastal-Image-Labeler/docs/code_documentation/database)

There are also some other questions I had. For these pages what would you like? Or should they be removed
[https://uncg-daisy.github.io/Coastal-Image-Labeler/docs/code_documentation/data_exporting](https://uncg-daisy.github.io/Coastal-Image-Labeler/docs/code_documentation/data_exporting)

[https://uncg-daisy.github.io/Coastal-Image-Labeler/docs/code_documentation/maintenance]
(https://uncg-daisy.github.io/Coastal-Image-Labeler/docs/code_documentation/maintenance)


Also on the [overview](https://uncg-daisy.github.io/Coastal-Image-Labeler/docs/user_documentation/userDocOverview#) page for user documentation the 2nd link, Current Data uploaded in the labeler, doesn't lead anywhere. Is there a page it should lead to?

**Comment by ebgoldstein** [comment]
-Mongo DB docs — describe all aspects of the mongoDB such as the structure that you have for it, all the fields, etc.

-Data export page — this can stay as a stub. I will fill it in as i learn to use PyMongo...
-Maintenance — is there anything we will need to do in the future? SSL cert will need to be redone in a year... anything else?

- current data — this should lead to a page... with links to the NOAA site and the Secoora site..

**Comment by ShahNafisRafique** [comment]
What is the link to the Secoora site again

**Comment by ebgoldstein** [comment]
https://secoora.org/webcat/

we should also highlight 2 tools:

psi collect form downloading the NOAA emergency response imagery,
and PyWebCAT for downloading the SECOORA images: https://github.com/UNCG-DAISY/PyWebCAT

**Comment by ShahNafisRafique** [comment]
Where should I highlick psi collect and PyWebCAT

**Comment by ebgoldstein** [comment]
When we mention the data in the labeler, I jsut want to mention that we built tools to be able to retrieve this data and work with it... I can do this

**Comment by ebgoldstein** [comment]
I think if you just write the NOAA blurb, I can add blurbs for everyhting else... we are aobut to get another dataset uploaded in the next week

**Comment by ShahNafisRafique** [comment]
Okay I can add a placeholder.

**Comment by ShahNafisRafique** [comment]
Okay I added a mini tutorial in my own words explaining what to do [here](https://uncg-daisy.github.io/Coastal-Image-Labeler/docs/docing_the_docs/indexId) to add docs.

There is also [this](https://v2.docusaurus.io/docs/installation) page to show how to install and [this](https://v2.docusaurus.io/docs/docs-introduction) which talks about adding pages. Its kind of a lot from their site so hopefully my mini tutorial is small enough. 

If you could also review the docs and see if there is anything else that needs to be done that be cool. @ebgoldstein

**Comment by ShahNafisRafique** [comment]
The pages that still need stuff are

- [ ] [Data Exporting](https://uncg-daisy.github.io/Coastal-Image-Labeler/docs/code_documentation/data_exporting)

- [ ] [Maintenance](https://uncg-daisy.github.io/Coastal-Image-Labeler/docs/code_documentation/maintenance)

- [ ] [Data Sources](https://uncg-daisy.github.io/Coastal-Image-Labeler/docs/user_documentation/data_sources)
