### ISSUE TITLE
Export script

### ISSUE THREAD

**Issue by ShahNafisRafique** [UNCG-DAISY/Coastal-Image-Labeler#77]
Write a script to export all collections of a given schema and also to act as a backup service

**Comment by ebgoldstein** [comment]
@ShahNafisRafique — this can be closed now with v1.0.7 of the CLI, correct?

**Comment by ShahNafisRafique** [comment]
I havent added the backup feature yet, where its a pure export

**Comment by ShahNafisRafique** [comment]
So I looked into how to have exporting and turns out Mongo has a export CLI part of their overall CLI package.

1. Download the CLI [here](https://www.mongodb.com/try/download/community?tck=docs_server)
2. Then CD to the `bin` folder for where ever it is installed, for me it was `C:\Program Files\MongoDB\Server\4.2\bin`
3. Then run
```bash
mongoexport --uri="XXXX"  --collection=catalogs  --out=C:\Users\Skool\Desktop\catalogs.json
```
where XXXX is the URI, just change collection and out file.
@ebgoldstein

**Comment by ebgoldstein** [comment]
ok, cool...great sleuthing @ShahNafisRafique!

(and btw —  i'm super excited for more nested `json` action!)

I'll close this, on behalf of mongodb's work solving the problem
