### ISSUE TITLE
Impact Type(s)

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#80]
There should be a 'None' box, and then we should require atleast 1 box to be checked

**Comment by ebgoldstein** [comment]
also, even when i select none i get this error (even though this point is moot): 
<img width="514" alt="Screen Shot 2020-06-09 at 9 40 02 AM" src="https://user-images.githubusercontent.com/5330599/84154524-39ec5680-aa35-11ea-97d3-cdf5e7af444a.png">

**Comment by ShahNafisRafique** [comment]
We can do this two ways

1. Have a none option and require atleast 1 check box to be selected (this however creates a weird issue where if they select `none` and something else)
2. My recommendation, keep these 4 options and if they select no options that defaults as none.

**Comment by ebgoldstein** [comment]
Option 2.

**Comment by ShahNafisRafique** [comment]
Changed DB, should be in effect.

**Comment by ebgoldstein** [comment]
works on the front end, I'm going to close this...
