### ISSUE TITLE
pop up re: cycle to next image

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#82]
I forget the answer to this Q: 
Do we need that pop up?

**Comment by ShahNafisRafique** [comment]
I just have that pop up so that the user knows the image was tagged successfully or if there was an error. Else the page refreshes and because it refreshes so quick and there is so little change visually (just ID of image changes) sometimes I couldn't tell that it actually refreshed.

**Comment by ebgoldstein** [comment]
i think it's best to remove that click... I atleast want to try it out w/o the pop up

**Comment by ebgoldstein** [comment]
ok, this works... 
because a user is scrolled to the bottom of the page when they hit the submit button, and the screen reset pushes you to the top of the page, there is a visual clue for the tagger that it is a new image.

**Comment by ShahNafisRafique** [comment]
I can maybe add a popup only if theres an error
