### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#83]
can you reinstate the colors?

<img width="487" alt="Screen Shot 2020-06-09 at 10 07 13 AM" src="https://user-images.githubusercontent.com/5330599/84157723-10352e80-aa39-11ea-9fb8-aafdefa38fb6.png">

**Comment by ShahNafisRafique** [comment]
Yes I can!

**Comment by ShahNafisRafique** [comment]
![colors](https://user-images.githubusercontent.com/38015120/84330555-b5452980-ab55-11ea-8ef8-8163f6008654.PNG)

**Comment by ebgoldstein** [comment]
looks rad!
