### ISSUE TITLE
pick 1 or more

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#84]
can you reinstate the 'pick one or more' text for impact and terrain

<img width="487" alt="Screen Shot 2020-06-09 at 10 07 13 AM" src="https://user-images.githubusercontent.com/5330599/84157854-335fde00-aa39-11ea-9233-953bc6031420.png">

**Comment by ShahNafisRafique** [comment]
I can easily place the error message like so
![label_req](https://user-images.githubusercontent.com/38015120/84159806-7cb12d00-aa3b-11ea-8910-39f75651863c.PNG)

**Comment by ebgoldstein** [comment]
this works. I think teh text should say:
"Select 1 or more"

**Comment by ShahNafisRafique** [comment]
Updated database, testing now, should work.

**Comment by ShahNafisRafique** [comment]
Updated production server, and it works. Close?

**Comment by ebgoldstein** [comment]
looks good... 1 minor change. terrain should say "Select 1 or more"

**Comment by ShahNafisRafique** [comment]
Updated DB

**Comment by ebgoldstein** [comment]
nice, i see it now
