### ISSUE TITLE
allow Auth0 sign in via Github

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Coastal-Image-Labeler#89]

**Comment by ShahNafisRafique** [comment]
[Link](https://auth0.com/docs/connections/social/devkeys?_ga=2.18739129.1408529876.1591748558-1305967960.1591005210 )

before I think we can add GitHub we should use the production auth for google, then I think it will allow for GitHub

[Link](https://auth0.com/docs/connections/social/github) instructions on how to add GitHub

**Comment by ebgoldstein** [comment]
i'm gonna close this for now...
